### ISSUE TITLE
install can't copy files from nonexistent directories

### ISSUE THREAD

**Issue by 8kat** [Eddio0141/unitas_setup_tool#58]
Hello Eddio,

when I run the install command, I get the following error:

```
[ERROR unitas_setup_tool] Could not copy UniTAS folder from unitas_setup_tool\UniTAS\stable\UniTAS_BepInEx_v0.5.0\UniTAS_BepInEx_v0.5.0\plugins\UniTAS to BepInEx\plugins\UniTAS
```

There are two reasons this error occurs:

1. UniTAS_BepInEx_v0.5.0 doesn't have a subdirectory named UniTAS_BepInEx_v0.5.0
2. The stable download of unitas/bepinex doesn't have the plugins directory

By removing the extra reference to UniTAS_BepInEx_v0.5.0, and not trying to copy the plugins directory, I'm able to run the command successfully.

**Comment by 8kat** [comment]
I can put in a PR or two for this if you'd like.

**Comment by Eddio0141** [comment]
Oh I see, I've overlooked that problem.
Also sure! I'm happy to accept a fix for that.
